# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TatoebaBuilder/Protobuf/links_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(TatoebaBuilder/Protobuf/links_data.proto\x12\x06mydata\"0\n\x04Pair\x12\x13\n\x0bsrcSentence\x18\x01 \x01(\r\x12\x13\n\x0btgtSentence\x18\x02 \x01(\r\"\'\n\x08PairList\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.mydata.Pair\"q\n\x07\x44\x61taMap\x12\'\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x19.mydata.DataMap.DataEntry\x1a=\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.mydata.PairList:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TatoebaBuilder.Protobuf.links_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAMAP_DATAENTRY._options = None
  _DATAMAP_DATAENTRY._serialized_options = b'8\001'
  _PAIR._serialized_start=52
  _PAIR._serialized_end=100
  _PAIRLIST._serialized_start=102
  _PAIRLIST._serialized_end=141
  _DATAMAP._serialized_start=143
  _DATAMAP._serialized_end=256
  _DATAMAP_DATAENTRY._serialized_start=195
  _DATAMAP_DATAENTRY._serialized_end=256
# @@protoc_insertion_point(module_scope)
